### ISSUE TITLE
Operators = OR not working. Has no effect.

### ISSUE THREAD

**Issue by fluxxagency** [rmorse/search-filter#7]
Using operators="OR" has no effect on our filtering. We have 5 fields and use  operators="OR,OR,OR,OR,OR" but nothing changes. It still seems to use AND.

**Comment by rmorse** [comment]
Hey @fluxxagency , are you updated to the latest version of the plugin?  there was a bug in previous versions regarding the operators which should now be addressed?

Do you have a link I could take a look at?

**Comment by Ciklum-marketing** [comment]
@fluxxagency , just try lowercase.

**Comment by kongolml** [comment]
@fluxxagency , just try lowercase.

**Comment by HandHugs** [comment]
I am also unable to use the OR operator. Any ideas? Here is my code: 
 <code>do_shortcode( '[searchandfilter post_types="products" taxonomies="search,filter,gender,collection,style,fit" headings=",Filter,Gender,Collection,Style,Fit" types=",radio,radio,radio,checkbox,checkbox" operators=",,,OR,OR,OR"]' );</code>

**Comment by kongolml** [comment]
@HandHugs , try operators=",,,or,or,or"

**Comment by HandHugs** [comment]
I tried both lower and uppercase. No luck! @kongolml

**Comment by rmorse** [comment]
@HandHugs - do you want the "OR" operator between your fields?  A common misconception is the way this works, the operators work "within" each field, so if you had a category field, and set it to use "OR", then any of the categories selected would be shown, as opposed to use "AND", where only posts which are contained in each category selected would be shown.

So to explain a little further - if you had a tag field, and a category field, and set them to both use "OR" - then you the results shown would be:

Any post within ANY of the categories selected AND within ANY of the tags selected.

To get set the relationship between the fields you could try using `pre_get_posts` (I think WP default is using AND) or alternatively this is available as an option in the Pro version.

I will be adding this as an option to the free version however I don't have any timelines for that just yet.

Thanks

**Comment by HandHugs** [comment]
I think i might be confused. What we have is a clothing line and we want people to select Men's or Womens (from a radio) and have that NARROW the results based on the selection. Then we want them to be able to check from say, short sleeve, long sleeve, hooded and/or tank tops. What we want to do is that if they have womens (from one taxonomy - radio/dropdown) and tank tops and hoodies selected (another taxonomy - checkbox), we want it to show all the tank tops AND all the hoodies that are marked as women's. Is that possible?

**Comment by HandHugs** [comment]
Anything?

**Comment by HandHugs** [comment]
I would love to know if I am understanding this correctly or not. To me changing the operators from AND to OR (or 'or') makes absolutely no difference in how the filter functions. If someone could at least explain how it should work, then I would be able to make it work for me. Anyone?

**Comment by kongolml** [comment]
@HandHugs , i think the point is that you can't use nested search, as it works as shortcodes, you should do some custom coding.

**Comment by rmorse** [comment]
@HandHugs - it sounds like what you are describing is the relationship between tags, categories and taxonomies - not the relationship within taxonomies and between the terms themselves (which is what the operators feature is for).

What you are after I believe is available in [Search & Filter Pro](http://www.designsandcode.com/wordpress-plugins/search-filter-pro/) - a new feature is also being added soon that will update the filters themselves (not just the results like you mention), so if you say select hoodies (and you have another taxonomy for "colour") - then the field for colour would only show available colours - hiding any colours that are not available for hoodies.

An alternative is to use [pre_get_posts](https://codex.wordpress.org/Plugin_API/Action_Reference/pre_get_posts) and try to modify the query itself so that the the relationship of taxonomy queries uses a different operator.

Thanks
