### ISSUE TITLE
Changing submit label has no effect

### ISSUE THREAD

**Issue by ninjapiraatti** [rmorse/search-filter#8]
When I change submit labe to my language ("etsi") and save the form, it reverts back to "submit".

**Comment by rmorse** [comment]
Can you paste the shortcode you are using here?

**Comment by ninjapiraatti** [comment]
[searchandfilter id="14395"]

On Mon, May 19, 2014 at 12:37 PM, Ross Morsali notifications@github.comwrote:

> Can you paste the shortcode you are using here?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rmorse/search-filter/issues/8#issuecomment-43482577
> .

## 

Tuomas Louekari https://twitter.com/PlanetoidiCom
Planetoidi.com
+358 44 329 2033

**Comment by rmorse** [comment]
Hey ninjapiraatti, can you open a ticket on the support forums (http://www.designsandcode.com/forums/forum/search-filter-pro/support/) - sorry I didn't realise you had purchased otherwise I would have replied quicker - but github is for the free version S & F

I'll look in to it right away once you open a ticket :)

**Comment by ninjapiraatti** [comment]
Ok, done.

On Tue, May 20, 2014 at 12:28 PM, Ross Morsali notifications@github.comwrote:

> Closed #8 https://github.com/rmorse/search-filter/issues/8.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rmorse/search-filter/issues/8#event-122814940
> .

## 

Tuomas Louekari https://twitter.com/PlanetoidiCom
Planetoidi.com
+358 44 329 2033
